spring.mongodb.uri=mongodb+srv://jaegeresp_db_user:tkQpKuOuimH53vM1@opencells-tasks.xlvtado.mongodb.net/taskmanager?appName=opencells-tasks
jwt.secret=433a7a4a642f8996df9e47840922efeecc1b2ce5396f3edbd55d337f37931dda
jwt.expiration-ms=86400000