spring.mongodb.uri=mongodb+srv://jaegeresp_db_user:9YEbpadqE5eY3zHM@opencells-tasks.xlvtado.mongodb.net/taskmanager?appName=opencells-tasks
jwt.secret=Nre/9y0SoePpAZz8UUbTSdy+OyPwll8ConMte2xYv04=
jwt.expiration-ms=86400000